export const users = [
    { id: 1, name: 'Jude Agboola', trans: '100', total: '1100', img: 'https://randomuser.me/api/portraits/men/33.jpg' },
    { id: 2, name: 'James Agboola', trans: '200', total: '750', img: 'https://randomuser.me/api/portraits/women/25.jpg' },
    { id: 3, name: 'Samuel Ocran', trans: '120', total: '2500', img: 'https://randomuser.me/api/portraits/women/86.jpg' },
    { id: 4, name: 'Ugo Amanoh', trans: '110', total: '34000', img: 'https://randomuser.me/api/portraits/women/2.jpg' },
    { id: 5, name: 'Author Pendragon', trans: '500', total: '1228', img: 'https://randomuser.me/api/portraits/women/51.jpg' },
    { id: 6, name: 'James Agboola', trans: '570', total: '1530', img: 'https://randomuser.me/api/portraits/men/17.jpg' },
    { id: 7, name: 'Samuel Ocran', trans: '590', total: '15360', img: 'https://randomuser.me/api/portraits/women/77.jpg' },
    { id: 8, name: 'Ugo Amanoh', trans: '50', total: '13350', img: 'https://randomuser.me/api/portraits/women/77.jpg' },
    { id: 9, name: 'Author Pendragon', trans: '50', total: '13350', img: 'https://randomuser.me/api/portraits/men/58.jpg' },
    { id: 10, name: 'Author Pendragon', trans: '700', total: '1450', img: 'https://randomuser.me/api/portraits/men/58.jpg' },
    { id: 11, name: 'Author Pendragon', trans: '700', total: '1450', img: 'https://randomuser.me/api/portraits/men/58.jpg' },
    { id: 12, name: 'Author Pendragon', trans: '700', total: '1450', img: 'https://randomuser.me/api/portraits/men/58.jpg' },
    { id: 13, name: 'Author Pendragon', trans: '700', total: '1450', img: 'https://randomuser.me/api/portraits/men/58.jpg' },
]